*.background=f2f2f2
*.foreground=000000
*.textBackground=cccccc
*.textForeground=000000
*.caretForeground=000000
*.inactiveBackground=ffffff
*.inactiveForeground=777777
*.selectionBackground=4A6EB7
*.selectionForeground=ffffff

control=e0e0e0
controlText=000000
infoText=000000
text=000000
textText=000000
window=f2f2f2
