*.background=3c3f41
*.foreground=bbbbbb
*.textBackground=3c3f41
*.textForeground=bbbbbb
*.caretForeground=bbbbbb
*.inactiveBackground=3C3F41
*.inactiveForeground=bbbbbb
*.selectionBackground=4B6EAF
*.selectionForeground=bbbbbb

control=3c3f41
controlText=bbbbbb
infoText=bbbbbb
text=bbbbbb
textText=bbbbbb
window=3c3f41
